backend:
  name: github
  repo: thusharadev97/bella-baby-lookbook-d7bc4d0d
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Journal Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Thushara Sanjeewa" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
