/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WriteForUsRouteImport } from './routes/write-for-us'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContributorRouteImport } from './routes/_authenticated/contributor'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ContributeIndexRouteImport } from './routes/contribute/index'
import { Route as ContributeSubmitRouteImport } from './routes/contribute/submit'
import { Route as EditorialSlugRouteImport } from './routes/editorial.$slug'
import { Route as EditorialWideLegTrousers2026RouteImport } from './routes/editorial.wide-leg-trousers-2026'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as MagazineCategoryRouteImport } from './routes/magazine.$category'
import { Route as TrendsCountryRouteImport } from './routes/trends_.$country'
import { Route as AuthenticatedAdminEditorialRouteImport } from './routes/_authenticated/admin_.editorial'
import { Route as AuthenticatedContributorDashboardRouteImport } from './routes/_authenticated/contributor_.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteForUsRoute = WriteForUsRouteImport.update({
  id: '/write-for-us',
  path: '/write-for-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContributorRoute =
  AuthenticatedContributorRouteImport.update({
    id: '/contributor',
    path: '/contributor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContributeRoute,
} as any)
const ContributeSubmitRoute = ContributeSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ContributeRoute,
} as any)
const EditorialSlugRoute = EditorialSlugRouteImport.update({
  id: '/editorial/$slug',
  path: '/editorial/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialWideLegTrousers2026Route =
  EditorialWideLegTrousers2026RouteImport.update({
    id: '/editorial/wide-leg-trousers-2026',
    path: '/editorial/wide-leg-trousers-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineCategoryRoute = MagazineCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MagazineRoute,
} as any)
const TrendsCountryRoute = TrendsCountryRouteImport.update({
  id: '/trends_/$country',
  path: '/trends/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEditorialRoute =
  AuthenticatedAdminEditorialRouteImport.update({
    id: '/admin_/editorial',
    path: '/admin/editorial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContributorDashboardRoute =
  AuthenticatedContributorDashboardRouteImport.update({
    id: '/contributor_/dashboard',
    path: '/contributor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/lookbook': typeof LookbookRoute
  '/magazine': typeof MagazineRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/write-for-us': typeof WriteForUsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contributor': typeof AuthenticatedContributorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/contribute/submit': typeof ContributeSubmitRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/editorial/wide-leg-trousers-2026': typeof EditorialWideLegTrousers2026Route
  '/journal/$slug': typeof JournalSlugRoute
  '/magazine/$category': typeof MagazineCategoryRoute
  '/trends/$country': typeof TrendsCountryRoute
  '/contribute/': typeof ContributeIndexRoute
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/contributor/dashboard': typeof AuthenticatedContributorDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/lookbook': typeof LookbookRoute
  '/magazine': typeof MagazineRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/write-for-us': typeof WriteForUsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contributor': typeof AuthenticatedContributorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/contribute/submit': typeof ContributeSubmitRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/editorial/wide-leg-trousers-2026': typeof EditorialWideLegTrousers2026Route
  '/journal/$slug': typeof JournalSlugRoute
  '/magazine/$category': typeof MagazineCategoryRoute
  '/trends/$country': typeof TrendsCountryRoute
  '/contribute': typeof ContributeIndexRoute
  '/admin/editorial': typeof AuthenticatedAdminEditorialRoute
  '/contributor/dashboard': typeof AuthenticatedContributorDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/lookbook': typeof LookbookRoute
  '/magazine': typeof MagazineRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trends': typeof TrendsRoute
  '/write-for-us': typeof WriteForUsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/contributor': typeof AuthenticatedContributorRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/contribute/submit': typeof ContributeSubmitRoute
  '/editorial/$slug': typeof EditorialSlugRoute
  '/editorial/wide-leg-trousers-2026': typeof EditorialWideLegTrousers2026Route
  '/journal/$slug': typeof JournalSlugRoute
  '/magazine/$category': typeof MagazineCategoryRoute
  '/trends_/$country': typeof TrendsCountryRoute
  '/contribute/': typeof ContributeIndexRoute
  '/_authenticated/admin_/editorial': typeof AuthenticatedAdminEditorialRoute
  '/_authenticated/contributor_/dashboard': typeof AuthenticatedContributorDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/lookbook'
    | '/magazine'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trends'
    | '/write-for-us'
    | '/admin'
    | '/contributor'
    | '/blog/$slug'
    | '/contribute/submit'
    | '/editorial/$slug'
    | '/editorial/wide-leg-trousers-2026'
    | '/journal/$slug'
    | '/magazine/$category'
    | '/trends/$country'
    | '/contribute/'
    | '/admin/editorial'
    | '/contributor/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/lookbook'
    | '/magazine'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trends'
    | '/write-for-us'
    | '/admin'
    | '/contributor'
    | '/blog/$slug'
    | '/contribute/submit'
    | '/editorial/$slug'
    | '/editorial/wide-leg-trousers-2026'
    | '/journal/$slug'
    | '/magazine/$category'
    | '/trends/$country'
    | '/contribute'
    | '/admin/editorial'
    | '/contributor/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/lookbook'
    | '/magazine'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trends'
    | '/write-for-us'
    | '/_authenticated/admin'
    | '/_authenticated/contributor'
    | '/blog_/$slug'
    | '/contribute/submit'
    | '/editorial/$slug'
    | '/editorial/wide-leg-trousers-2026'
    | '/journal/$slug'
    | '/magazine/$category'
    | '/trends_/$country'
    | '/contribute/'
    | '/_authenticated/admin_/editorial'
    | '/_authenticated/contributor_/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LookbookRoute: typeof LookbookRoute
  MagazineRoute: typeof MagazineRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrendsRoute: typeof TrendsRoute
  WriteForUsRoute: typeof WriteForUsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EditorialSlugRoute: typeof EditorialSlugRoute
  EditorialWideLegTrousers2026Route: typeof EditorialWideLegTrousers2026Route
  JournalSlugRoute: typeof JournalSlugRoute
  TrendsCountryRoute: typeof TrendsCountryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write-for-us': {
      id: '/write-for-us'
      path: '/write-for-us'
      fullPath: '/write-for-us'
      preLoaderRoute: typeof WriteForUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contributor': {
      id: '/_authenticated/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof AuthenticatedContributorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof ContributeRoute
    }
    '/contribute/submit': {
      id: '/contribute/submit'
      path: '/submit'
      fullPath: '/contribute/submit'
      preLoaderRoute: typeof ContributeSubmitRouteImport
      parentRoute: typeof ContributeRoute
    }
    '/editorial/$slug': {
      id: '/editorial/$slug'
      path: '/editorial/$slug'
      fullPath: '/editorial/$slug'
      preLoaderRoute: typeof EditorialSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/wide-leg-trousers-2026': {
      id: '/editorial/wide-leg-trousers-2026'
      path: '/editorial/wide-leg-trousers-2026'
      fullPath: '/editorial/wide-leg-trousers-2026'
      preLoaderRoute: typeof EditorialWideLegTrousers2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine/$category': {
      id: '/magazine/$category'
      path: '/$category'
      fullPath: '/magazine/$category'
      preLoaderRoute: typeof MagazineCategoryRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/trends_/$country': {
      id: '/trends_/$country'
      path: '/trends/$country'
      fullPath: '/trends/$country'
      preLoaderRoute: typeof TrendsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/editorial': {
      id: '/_authenticated/admin_/editorial'
      path: '/admin/editorial'
      fullPath: '/admin/editorial'
      preLoaderRoute: typeof AuthenticatedAdminEditorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contributor_/dashboard': {
      id: '/_authenticated/contributor_/dashboard'
      path: '/contributor/dashboard'
      fullPath: '/contributor/dashboard'
      preLoaderRoute: typeof AuthenticatedContributorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContributorRoute: typeof AuthenticatedContributorRoute
  AuthenticatedAdminEditorialRoute: typeof AuthenticatedAdminEditorialRoute
  AuthenticatedContributorDashboardRoute: typeof AuthenticatedContributorDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContributorRoute: AuthenticatedContributorRoute,
  AuthenticatedAdminEditorialRoute: AuthenticatedAdminEditorialRoute,
  AuthenticatedContributorDashboardRoute:
    AuthenticatedContributorDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MagazineRouteChildren {
  MagazineCategoryRoute: typeof MagazineCategoryRoute
}

const MagazineRouteChildren: MagazineRouteChildren = {
  MagazineCategoryRoute: MagazineCategoryRoute,
}

const MagazineRouteWithChildren = MagazineRoute._addFileChildren(
  MagazineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  LookbookRoute: LookbookRoute,
  MagazineRoute: MagazineRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrendsRoute: TrendsRoute,
  WriteForUsRoute: WriteForUsRoute,
  BlogSlugRoute: BlogSlugRoute,
  EditorialSlugRoute: EditorialSlugRoute,
  EditorialWideLegTrousers2026Route: EditorialWideLegTrousers2026Route,
  JournalSlugRoute: JournalSlugRoute,
  TrendsCountryRoute: TrendsCountryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
